### ISSUE TITLE
Registering server fails after URL check

### ISSUE THREAD

**Issue by arychj** [wallabag/ios-app#165]
| Q             | A
| ------------- | ---
| Device?       | iPad
| Device Os version    | 12.1.1
| App Version   | 3.0.3
| Wallabag server version | 2.3.6-dev

### Steps to reproduce/test case

* Launch app
* Enter server
* Tap "Next"

### Description
After installing a new server, I am unable to register it with the iOS app. I am able to browse to and log into the Wallabag via the web, and also via Android.

A check of the server logs reveals that the app is reaching out:
```xxx.xxx.xxx.xxx - - [11/Jan/2019:15:12:11 -0600] "GET /api/version HTTP/1.1" 200 2127 "-" "wallabag/3.0.3 (fr.district-web.wallabag; build:128; iOS 12.1.1) Alamofire/4.8.0"```

However, after that the app errors out with "Whoops looks like something went wrong. Check the url, don't forget http or https"

**Comment by fuenfnull** [comment]
Same here with wallabag server 2.2.3 since iOS App 3.0.1

**Comment by fuenfnull** [comment]
Nope. 3.0.3 (with iOS 12.1.1) did not work for me eitler.

**Comment by ducatdusk** [comment]
I'm experiencing the same issue with 3.03.

**Comment by bourvill** [comment]
@ducatdusk server version ?

**Comment by rapedapeda** [comment]
Same here. Server 2.3.6, iOS 12.1.2 and Apo version 3.0.3.

**Comment by ducatdusk** [comment]
> @ducatdusk server version ?

2.3.6

**Comment by arychj** [comment]
Unfortunately no. I've pulled down the `3.0.4` release, but I'm still getting the "Whoops looks like something went wrong..." error.

Could it be because I'm on a `-dev` version of the server?

**Comment by arychj** [comment]
Okay, I checked out the `2.3.6` tag of the server and it's working now. Thank you!

Is there an option to enable dev release compatibility, or to simply ignore the dev tag? I ask because the server installation instructions have you implicitly checking out `master`, which is currently on `2.3.6-dev`, and per the changelog it looks like they did the same dev jump on the `2.3.5` release as well.

**Comment by fuenfnull** [comment]
Server 2.2.3 does not work with ios-App3.0.4, so i have upgraded to Server 2.3.5 and then 2.3.6. 
Now: fixed.

**Comment by jeanregisser** [comment]
Current App Store version 3.0.4 can't register with https://app.wallabag.it which is running 2.3.8-dev as of now.

![img_1788](https://user-images.githubusercontent.com/57791/53891988-ba9af680-402b-11e9-85fb-97e279219d07.PNG)

@bourvill do you plan to submit an update to fix this?

Thanks

**Comment by jeanregisser** [comment]
Looks like the change in https://github.com/wallabag/ios-app/commit/cdf1268e88811da504a33dd5ea50d1b0bda7a504 will fix this.

**Comment by bourvill** [comment]
Yes, release 4.0.0 fix the problem. I work hard to finish this version quickly. Sorry for the inconveniance

**Comment by arychj** [comment]
@bourvill Thanks for all your hard work!

**Comment by NiTRoeSE** [comment]
Hi, i can also not add my Server in the iOS App.
Server Version: (git 9796a3a) / 2.3.7 
Server runs fine so far, login works in browser... i dont change anything in last weeks, maybe the register problem exists longer but i just noticed it now because i installed app on new device. 
Thanks for help and the work on this app. :)

**Comment by ebal** [comment]
Hello everyone,

Q | A
-- | --
Device? | iPad
Device Os version | 12.2
App Version | 3.0.4
Wallabag server version | 2.3.7

I am also getting the same error msg as jeanregisser mentioned above (see image).

    Whoops looks like something went wrong.

On my server, I see:

    "GET /api/version HTTP/1.1" 200 27 "-" "wallabag/3.0.4 (fr.district-web.wallabag; build:129; iOS 12.2.0) Alamofire/4.8.0"

thank you

**Comment by bourvill** [comment]
New release with this fix is ready, but I have problem on some device, app crash on start. 

I release the 4.0.0 version soon

**Comment by ebal** [comment]
Confirm, v4.0.0 works as advertised.
thanks

**Comment by bourvill** [comment]
Fixed in 4.0.0

**Comment by j0k3r** [comment]
Looks like people still have that bug using app.wallabag.it. I just checked and got the same error.
Any idea?

**Comment by bourvill** [comment]
I disable the feature that cause this problem.
For information on registration, i will check the version of the server. wallabag.it run as 2.3.8-dev and this version is not in whilelist. But this feature is to restritive, some users may use for dev.
I will rewrite this part shortly.

**Comment by bourvill** [comment]
@j0k3r 4.0.1 is submitted to apple.

**Comment by bourvill** [comment]
4.0.1 is released 🚀

**Comment by sdeleuze** [comment]
4.0.1 fixed the server check issue but I have just a list of empty articles with app.wallabag.it. Did you test it with the main server ? Should I create an issue ?

**Comment by sdeleuze** [comment]
Server check issue fixed indeed, thanks.

**Comment by j0k3r** [comment]
Fixed!
👏 @bourvill
