### ISSUE TITLE
 Wrong url in the iOS application

### ISSUE THREAD

**Issue by tcitworld** [wallabag/ios-app#24]
@nicosomb has changed the URL for doc lately.

>When you use the ios application, there is a problem with the URL. There are wrong. Should be changed to avoid falling on error pages.
>
>Wrong URL are =
>wallaby FAQ: https://www.wallabag.org/frequently-asked-questions/
>Install your own wallabag: http://doc.wallabag.org/doku.php?id=users:begin:install

>![](https://cloud.githubusercontent.com/assets/1076038/5756261/b1d6efb6-9cad-11e4-9d47-6c01dd6acedd.PNG)

**Comment by kevmeyer** [comment]
should be fixed.  
Maybe i should write a guide how to configure the iOS App as well.

**Comment by kevmeyer** [comment]
We could use some perma-links, which will redirect the users to the current doc-URLs (since they tend to change over time).  
Something like tiny.cc (they claim to let you change the destination URL at any time) or simply a self-made redirection.

**Comment by tcitworld** [comment]
@nicosomb owns the wllbg.org domain name (today, only used for downloading vendor package)

**Comment by nicosomb** [comment]
And for downloading the latest version of wallabag ;-)

**Comment by tcitworld** [comment]
So can we have wllbg.org/doc ?

**Comment by nicosomb** [comment]
Yes we can. In fact, I use https://github.com/YOURLS/YOURLS for wllbg.org.

**Comment by nicosomb** [comment]
Done http://wllbg.org/doc

**Comment by tcitworld** [comment]
I like this app. ;-)

**Comment by ronnicek** [comment]
Link to "install your own wallabag" is still wrong (there is Download instead of download in link and it shows 404)
